name: listenbrainz
version: '0.0.1'
title: ListenBrainz
summary: ListenBrainz Now Playing Viewer
description: |
  ListenBrainz Now Playing Viewer
base: core20
confinement: strict
grade: devel

apps:
  listenbrainz:
    command: listenbrainz/listenbrainz --no-sandbox
    extensions: [gnome-3-38]
    plugs:
    - browser-support
    - network
    - network-bind
    environment:
      # Correct the TMPDIR path for Chromium Framework/Electron to ensure
      # libappindicator has readable resources.
      TMPDIR: $XDG_RUNTIME_DIR

parts:
  listenbrainz-now-playing:
    plugin: nil
    source: https://github.com/metabrainz/listenbrainz-now-playing.git
    override-build: |
        npm install electron electron-packager
        npx electron-packager . --overwrite --platform=linux --output=release-build --prune=true
        cp -rv ./listenbrainz-linux-* $SNAPCRAFT_PART_INSTALL/listenbrainz
        chmod ugo+rwx $SNAPCRAFT_PART_INSTALL/listenbrainz
    build-snaps:
    - node/18/stable
    build-packages:
    - unzip
    stage-packages:
    - libnss3
    - libnspr4
